var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/automation/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d34ff2ce._.js")
R.c("server/chunks/ssr/9e883_next_dist_b00f2518._.js")
R.c("server/chunks/ssr/frontend_5351a2fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4e0a03fb._.js")
R.c("server/chunks/ssr/9e883_next_dist_984aa78a._.js")
R.c("server/chunks/ssr/9e883_next_dist_596e9b5c._.js")
R.c("server/chunks/ssr/9e883_next_dist_89abee15._.js")
R.c("server/chunks/ssr/frontend_app_f2796388._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_global-error_c00881b3.js")
R.c("server/chunks/ssr/frontend_dc5defeb._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_34a976ba._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_forbidden_520cb951.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_unauthorized_62f331ea.js")
R.c("server/chunks/ssr/frontend_app_(dashboard)_layout_tsx_e4e4817c._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_(dashboard)_automation_page_actions_ea94a328.js")
R.m(32757)
module.exports=R.m(32757).exports
