// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-training" | "/analytics" | "/auth/forgot" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/auth/verify-email" | "/automation" | "/autonomous" | "/billing" | "/billing/cancel" | "/billing/success" | "/booking" | "/booking-calendar" | "/clients" | "/comment-automation" | "/conversations" | "/crm" | "/dashboard" | "/dashboard/settings/security" | "/help" | "/integrations/meta/callback" | "/knowledge-base" | "/leads" | "/pricing" | "/settings" | "/settings/profile" | "/settings/security" | "/support"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/ai-training": {}
  "/analytics": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/auth": {}
  "/auth/forgot": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/auth/verify-email": {}
  "/automation": {}
  "/autonomous": {}
  "/billing": {}
  "/billing/cancel": {}
  "/billing/success": {}
  "/booking": {}
  "/booking-calendar": {}
  "/clients": {}
  "/comment-automation": {}
  "/conversations": {}
  "/crm": {}
  "/dashboard": {}
  "/dashboard/settings/security": {}
  "/help": {}
  "/integrations/meta/callback": {}
  "/knowledge-base": {}
  "/leads": {}
  "/pricing": {}
  "/settings": {}
  "/settings/profile": {}
  "/settings/security": {}
  "/support": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
