import assert from "node:assert/strict";
import { hashPasswordWorker, verifyPasswordWorker } from "../utils/bcryptWorker";

type TestCase = {
  name: string;
  run: () => void | Promise<void>;
};

export const bcryptMigrationTests: TestCase[] = [
  {
    name: "bcryptjs hashing and verification (feature flag disabled)",
    run: async () => {
      const originalFlag = process.env.AUTH_NATIVE_BCRYPT_ENABLED;
      process.env.AUTH_NATIVE_BCRYPT_ENABLED = "false";
      try {
        const password = "TestPassword123!";
        const hash = await hashPasswordWorker(password, 10);
        
        // bcryptjs v3 produces $2b$ format hashes by default
        assert.ok(hash.startsWith("$2b$") || hash.startsWith("$2a$"), `Expected hash to start with $2b$ or $2a$, got: ${hash}`);
        
        const isMatch = await verifyPasswordWorker(password, hash);
        assert.equal(isMatch, true, "Expected password to verify successfully with bcryptjs");
        
        const isWrongMatch = await verifyPasswordWorker("WrongPassword!", hash);
        assert.equal(isWrongMatch, false, "Expected wrong password to fail verification");
      } finally {
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = originalFlag;
      }
    },
  },
  {
    name: "native bcrypt hashing and verification (feature flag enabled)",
    run: async () => {
      const originalFlag = process.env.AUTH_NATIVE_BCRYPT_ENABLED;
      process.env.AUTH_NATIVE_BCRYPT_ENABLED = "true";
      try {
        const password = "TestPassword123!";
        const hash = await hashPasswordWorker(password, 10);
        
        // native bcrypt produces $2b$ format hashes by default
        assert.ok(hash.startsWith("$2b$") || hash.startsWith("$2a$"), `Expected hash to start with $2b$ or $2a$, got: ${hash}`);
        
        const isMatch = await verifyPasswordWorker(password, hash);
        assert.equal(isMatch, true, "Expected password to verify successfully with native bcrypt");
        
        const isWrongMatch = await verifyPasswordWorker("WrongPassword!", hash);
        assert.equal(isWrongMatch, false, "Expected wrong password to fail verification");
      } finally {
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = originalFlag;
      }
    },
  },
  {
    name: "cross-library compatibility verification",
    run: async () => {
      const originalFlag = process.env.AUTH_NATIVE_BCRYPT_ENABLED;
      
      try {
        const password = "CrossLibPassword123!";
        
        // 1. Generate hash using bcryptjs ($2b$)
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = "false";
        const jsHash = await hashPasswordWorker(password, 10);
        assert.ok(jsHash.startsWith("$2b$") || jsHash.startsWith("$2a$"));
        
        // Verify with native bcrypt
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = "true";
        const verifiedByNative = await verifyPasswordWorker(password, jsHash);
        assert.equal(verifiedByNative, true, "Native bcrypt should be able to verify hashes generated by bcryptjs");
        
        // 2. Generate hash using native bcrypt ($2b$)
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = "true";
        const nativeHash = await hashPasswordWorker(password, 10);
        assert.ok(nativeHash.startsWith("$2b$") || nativeHash.startsWith("$2a$"));
        
        // Verify with bcryptjs
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = "false";
        const verifiedByJs = await verifyPasswordWorker(password, nativeHash);
        assert.equal(verifiedByJs, true, "Bcryptjs should be able to verify hashes generated by native bcrypt");
        
      } finally {
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = originalFlag;
      }
    },
  },
  {
    name: "worker thread fallback path verification",
    run: async () => {
      const originalFlag = process.env.AUTH_NATIVE_BCRYPT_ENABLED;
      const workerThreads = require("worker_threads");
      const originalWorker = workerThreads.Worker;

      // Force worker thread creation to throw, simulating environments where Worker is restricted or fails
      workerThreads.Worker = class FailingWorker {
        constructor() {
          throw new Error("Simulated worker thread spawn failure");
        }
      } as any;

      try {
        const password = "FallbackPassword123!";
        
        // 1. Verify hashing still works using fallback
        const hash = await hashPasswordWorker(password, 10);
        assert.ok(hash.startsWith("$2b$") || hash.startsWith("$2a$"));

        // 2. Verify verification still works using fallback
        const isMatch = await verifyPasswordWorker(password, hash);
        assert.equal(isMatch, true, "Expected verification to succeed via fallback path");

        const isWrongMatch = await verifyPasswordWorker("Wrong!", hash);
        assert.equal(isWrongMatch, false, "Expected wrong password to fail via fallback path");
      } finally {
        workerThreads.Worker = originalWorker;
        process.env.AUTH_NATIVE_BCRYPT_ENABLED = originalFlag;
      }
    },
  },
];
