var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/integrations/meta/callback/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cbdd1c9._.js")
R.c("server/chunks/ssr/9e883_next_dist_b00f2518._.js")
R.c("server/chunks/ssr/frontend_4e20259b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4e0a03fb._.js")
R.c("server/chunks/ssr/9e883_next_dist_984aa78a._.js")
R.c("server/chunks/ssr/9e883_next_dist_596e9b5c._.js")
R.c("server/chunks/ssr/9e883_next_dist_89abee15._.js")
R.c("server/chunks/ssr/frontend_app_f2796388._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_global-error_c00881b3.js")
R.c("server/chunks/ssr/frontend_dc5defeb._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_34a976ba._.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_forbidden_520cb951.js")
R.c("server/chunks/ssr/9e883_next_dist_client_components_builtin_unauthorized_62f331ea.js")
R.c("server/chunks/ssr/ceffb__next-internal_server_app_integrations_meta_callback_page_actions_ec7ba731.js")
R.m(5415)
module.exports=R.m(5415).exports
