import express from "express";
import { protect } from "../middleware/auth.middleware";
import { requirePermission } from "../middleware/rbac.middleware";
import {
  applyConnectHubOverride,
  assignConnectHubSeat,
  connectInstagramHub,
  connectWhatsAppHub,
  expireConnectHubToken,
  getConnectHubDashboard,
  getIntegrationDiagnostics,
  getIntegrations,
  getInstagramAccounts,
  getOnboarding,
  installConnectHubMarketplaceArtifact,
  meterConnectHubFeatureGate,
  promoteSandboxConnectHubIntegration,
  provisionConnectHubTenant,
  recoverConnectHubWebhook,
  refreshConnectHubToken,
  retryConnectDiagnostic,
  rollbackConnectHubMarketplaceArtifact,
  runConnectHubSelfAudit,
  runWhatsAppDoctor,
  saveConnectHubWizardProgress,
  upsertConnectHubBranding,
  upgradeConnectHubPlan,
} from "../controllers/integration.controller";

const router = express.Router();

router.get("/onboarding", protect, getOnboarding);
router.get("/instagram/accounts", protect, getInstagramAccounts);
router.get(
  "/connect-hub",
  protect,
  requirePermission("settings:view"),
  getConnectHubDashboard
);
router.post(
  "/connect-hub/provision",
  protect,
  requirePermission("settings:manage"),
  provisionConnectHubTenant
);
router.post(
  "/connect-hub/connect/instagram",
  protect,
  requirePermission("settings:manage"),
  connectInstagramHub
);
router.post(
  "/connect-hub/connect/whatsapp",
  protect,
  requirePermission("settings:manage"),
  connectWhatsAppHub
);
router.post(
  "/connect-hub/connect/whatsapp/doctor",
  protect,
  requirePermission("settings:manage"),
  runWhatsAppDoctor
);
router.get(
  "/connect-hub/diagnostics/:provider",
  protect,
  requirePermission("settings:view"),
  getIntegrationDiagnostics
);
router.post(
  "/connect-hub/diagnostics/retry",
  protect,
  requirePermission("settings:manage"),
  retryConnectDiagnostic
);
router.post(
  "/connect-hub/wizard/progress",
  protect,
  requirePermission("settings:manage"),
  saveConnectHubWizardProgress
);
router.post(
  "/connect-hub/feature-gate/meter",
  protect,
  requirePermission("settings:manage"),
  meterConnectHubFeatureGate
);
router.post(
  "/connect-hub/upgrade",
  protect,
  requirePermission("settings:manage"),
  upgradeConnectHubPlan
);
router.post(
  "/connect-hub/sandbox/promote",
  protect,
  requirePermission("settings:manage"),
  promoteSandboxConnectHubIntegration
);
router.post(
  "/connect-hub/token/refresh",
  protect,
  requirePermission("settings:manage"),
  refreshConnectHubToken
);
router.post(
  "/connect-hub/token/expire",
  protect,
  requirePermission("settings:manage"),
  expireConnectHubToken
);
router.post(
  "/connect-hub/webhook/recover",
  protect,
  requirePermission("settings:manage"),
  recoverConnectHubWebhook
);
router.post(
  "/connect-hub/branding",
  protect,
  requirePermission("settings:manage"),
  upsertConnectHubBranding
);
router.post(
  "/connect-hub/marketplace/install",
  protect,
  requirePermission("settings:manage"),
  installConnectHubMarketplaceArtifact
);
router.post(
  "/connect-hub/marketplace/rollback",
  protect,
  requirePermission("settings:manage"),
  rollbackConnectHubMarketplaceArtifact
);
router.post(
  "/connect-hub/seats/assign",
  protect,
  requirePermission("settings:manage"),
  assignConnectHubSeat
);
router.post(
  "/connect-hub/overrides",
  protect,
  requirePermission("settings:manage"),
  applyConnectHubOverride
);
router.get(
  "/connect-hub/self-audit",
  protect,
  requirePermission("settings:view"),
  runConnectHubSelfAudit
);
router.get("/", protect, requirePermission("settings:view"), getIntegrations);

export default router;
