import express from "express";
import { protect } from "../middleware/auth.middleware";
import { requirePermission } from "../middleware/rbac.middleware";
import {
  applyDeveloperPlatformOverride,
  applyDeveloperPlatformPolicy,
  applyConnectHubOverride,
  assignConnectHubSeat,
  bindDeveloperPlatformSecret,
  connectInstagramHub,
  connectWhatsAppHub,
  createDeveloperPlatformApiKey,
  expireConnectHubToken,
  getDeveloperPlatformDashboard,
  getConnectHubDashboard,
  getIntegrationDiagnostics,
  getIntegrations,
  getInstagramAccounts,
  getOnboarding,
  installDeveloperPlatformPackage,
  invokeDeveloperPlatformPackageAction,
  installConnectHubMarketplaceArtifact,
  meterConnectHubFeatureGate,
  publishDeveloperPlatformPackage,
  publishDeveloperPlatformRelease,
  promoteSandboxConnectHubIntegration,
  provisionConnectHubTenant,
  registerDeveloperPlatformNamespace,
  recoverConnectHubWebhook,
  revokeDeveloperPlatformApiKey,
  refreshConnectHubToken,
  runMetaColdBootReconcile,
  runMetaDoctor,
  runMetaTokenLifecycle,
  retryConnectDiagnostic,
  rollbackConnectHubMarketplaceArtifact,
  runDeveloperPlatformExtensibilitySelfAudit,
  runConnectHubSelfAudit,
  runWhatsAppDoctor,
  seedMetaReviewerDemo,
  generateMetaReviewPack,
  saveConnectHubWizardProgress,
  subscribeDeveloperPlatformEvent,
  upsertConnectHubBranding,
  upgradeConnectHubPlan,
} from "../controllers/integration.controller";

const router = express.Router();

router.get("/onboarding", protect, getOnboarding);
router.get("/instagram/accounts", protect, getInstagramAccounts);
router.get(
  "/connect-hub",
  protect,
  requirePermission("settings:view"),
  getConnectHubDashboard
);
router.post(
  "/connect-hub/provision",
  protect,
  requirePermission("settings:manage"),
  provisionConnectHubTenant
);
router.post(
  "/connect-hub/connect/instagram",
  protect,
  requirePermission("settings:manage"),
  connectInstagramHub
);
router.post(
  "/connect-hub/connect/whatsapp",
  protect,
  requirePermission("settings:manage"),
  connectWhatsAppHub
);
router.post(
  "/connect-hub/connect/whatsapp/doctor",
  protect,
  requirePermission("settings:manage"),
  runWhatsAppDoctor
);
router.post(
  "/connect-hub/connect/meta/doctor",
  protect,
  requirePermission("settings:manage"),
  runMetaDoctor
);
router.post(
  "/connect-hub/reconcile/cold-boot",
  protect,
  requirePermission("settings:manage"),
  runMetaColdBootReconcile
);
router.post(
  "/connect-hub/token/sweep",
  protect,
  requirePermission("settings:manage"),
  runMetaTokenLifecycle
);
router.post(
  "/connect-hub/reviewer/seed",
  protect,
  requirePermission("settings:manage"),
  seedMetaReviewerDemo
);
router.get(
  "/connect-hub/reviewer/pack",
  protect,
  requirePermission("settings:view"),
  generateMetaReviewPack
);
router.get(
  "/connect-hub/diagnostics/:provider",
  protect,
  requirePermission("settings:view"),
  getIntegrationDiagnostics
);
router.post(
  "/connect-hub/diagnostics/retry",
  protect,
  requirePermission("settings:manage"),
  retryConnectDiagnostic
);
router.post(
  "/connect-hub/wizard/progress",
  protect,
  requirePermission("settings:manage"),
  saveConnectHubWizardProgress
);
router.post(
  "/connect-hub/feature-gate/meter",
  protect,
  requirePermission("settings:manage"),
  meterConnectHubFeatureGate
);
router.post(
  "/connect-hub/upgrade",
  protect,
  requirePermission("settings:manage"),
  upgradeConnectHubPlan
);
router.post(
  "/connect-hub/sandbox/promote",
  protect,
  requirePermission("settings:manage"),
  promoteSandboxConnectHubIntegration
);
router.post(
  "/connect-hub/token/refresh",
  protect,
  requirePermission("settings:manage"),
  refreshConnectHubToken
);
router.post(
  "/connect-hub/token/expire",
  protect,
  requirePermission("settings:manage"),
  expireConnectHubToken
);
router.post(
  "/connect-hub/webhook/recover",
  protect,
  requirePermission("settings:manage"),
  recoverConnectHubWebhook
);
router.post(
  "/connect-hub/branding",
  protect,
  requirePermission("settings:manage"),
  upsertConnectHubBranding
);
router.post(
  "/connect-hub/marketplace/install",
  protect,
  requirePermission("settings:manage"),
  installConnectHubMarketplaceArtifact
);
router.post(
  "/connect-hub/marketplace/rollback",
  protect,
  requirePermission("settings:manage"),
  rollbackConnectHubMarketplaceArtifact
);
router.post(
  "/connect-hub/seats/assign",
  protect,
  requirePermission("settings:manage"),
  assignConnectHubSeat
);
router.post(
  "/connect-hub/overrides",
  protect,
  requirePermission("settings:manage"),
  applyConnectHubOverride
);
router.get(
  "/connect-hub/self-audit",
  protect,
  requirePermission("settings:view"),
  runConnectHubSelfAudit
);
router.get(
  "/connect-hub/developer-platform",
  protect,
  requirePermission("settings:view"),
  getDeveloperPlatformDashboard
);
router.post(
  "/connect-hub/developer-platform/namespaces",
  protect,
  requirePermission("settings:manage"),
  registerDeveloperPlatformNamespace
);
router.post(
  "/connect-hub/developer-platform/packages/publish",
  protect,
  requirePermission("settings:manage"),
  publishDeveloperPlatformPackage
);
router.post(
  "/connect-hub/developer-platform/releases/publish",
  protect,
  requirePermission("settings:manage"),
  publishDeveloperPlatformRelease
);
router.post(
  "/connect-hub/developer-platform/packages/install",
  protect,
  requirePermission("settings:manage"),
  installDeveloperPlatformPackage
);
router.post(
  "/connect-hub/developer-platform/secrets/bind",
  protect,
  requirePermission("settings:manage"),
  bindDeveloperPlatformSecret
);
router.post(
  "/connect-hub/developer-platform/subscriptions",
  protect,
  requirePermission("settings:manage"),
  subscribeDeveloperPlatformEvent
);
router.post(
  "/connect-hub/developer-platform/invoke",
  protect,
  requirePermission("settings:manage"),
  invokeDeveloperPlatformPackageAction
);
router.post(
  "/connect-hub/developer-platform/policies",
  protect,
  requirePermission("settings:manage"),
  applyDeveloperPlatformPolicy
);
router.post(
  "/connect-hub/developer-platform/overrides",
  protect,
  requirePermission("settings:manage"),
  applyDeveloperPlatformOverride
);
router.post(
  "/connect-hub/developer-platform/api-keys/create",
  protect,
  requirePermission("settings:manage"),
  createDeveloperPlatformApiKey
);
router.post(
  "/connect-hub/developer-platform/api-keys/revoke",
  protect,
  requirePermission("settings:manage"),
  revokeDeveloperPlatformApiKey
);
router.get(
  "/connect-hub/developer-platform/self-audit",
  protect,
  requirePermission("settings:view"),
  runDeveloperPlatformExtensibilitySelfAudit
);
router.get("/", protect, requirePermission("settings:view"), getIntegrations);

export default router;
